eureka:
  client:
      serviceUrl:
          defaultZone: http://user:pass@localhost:8761/eureka/
spring:   
  datasource:
      url : jdbc:mysql://localhost/db_smartcafe
      username: root
      password: admin1234
      driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8006
minio:
  host: localhost
  port: 9000
  access-key: DVIOKS3IRD86I7V18WHK
  secret-key: Gf9Oeaq2BtOJ0DamzsbkmPL+e2DbJwyHzl7ZPQxa
  bucket-name:
    qr: qrcode
    tempat: tempat